DATA:
  data_name: ipad_scaned
  data_root: dataset/ipad_scaned/label_data
  fea_dim: 3
  voxel_size: 0.04
  voxel_max: 80000
  loop: 10

TRAIN:
  arch: pointtransformer_seg_repro
  use_xyz: True
  sync_bn: False
  ignore_label: 255
  train_gpu: [3]
  workers: 16  # data loader workers
  batch_size: 1  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.5
  epochs: 200
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  drop_rate: 0.5
  manual_seed: 7777
  print_freq: 1
  save_freq: 1
  save_path:
  weight: /data1/liuxinchen/point-transformer/exp/s3dis/pointtransformer_repro_norgb_2cls_v3/model/model_last.pth
  # resume: /home/liuxinchen/point-transformer-ipadscan/exp/ipad_scaned/baseline3/model/model_last.pth # path to latest checkpoint (default: none)
  resume: 
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
Distributed:
  dist_url: tcp://localhost:8888
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_list: dataset/s3dis/list/val5.txt
  test_list_full: dataset/s3dis/list/val5_full.txt
  split: val  # split in [train, val and test]
  test_gpu: [0]
  test_workers: 4
  batch_size_test: 4
  model_path:
  save_folder:
  names_path: data/s3dis/s3dis_names.txt
